# Generated by Django 4.1.13 on 2025-02-10 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_shift_end_time_alter_shift_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.port'),
        ),
    ]
