# Generated by Django 4.1 on 2025-02-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_employee_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='remote_checkin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='designation',
            name='user_type',
            field=models.CharField(default='USER', max_length=100),
        ),
    ]
