# Generated by Django 4.1 on 2025-02-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_designation_remote_checkin_designation_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_type',
            field=models.CharField(default='REGULAR', max_length=20),
        ),
    ]
