# Generated by Django 4.1 on 2025-02-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_attendance_attendance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(default=None),
        ),
    ]
