# Generated by Django 4.1 on 2025-02-15 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_attendance_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.employee'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.shift'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.designation'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.port'),
        ),
        migrations.AlterField(
            model_name='site',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.port'),
        ),
    ]
